CREATE TABLE IF NOT EXISTS `f_invoices` (
     `ID` INT(10) NOT NULL AUTO_INCREMENT,
     `CONTRAGENT` VARCHAR(256),
     `NOMER` VARCHAR(256),
     `SUMMA` FLOAT,
     `DATE` DATE,
     PRIMARY KEY (ID)
);